version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dbPassword}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - voronka_db_data:/var/lib/postgresql/data:rw
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "50076:5432"

volumes:
  voronka_db_data: